<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Roadmap;

class RoadmapSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [1, 1, 1, 'Pengantar SI', 'Fondasi', 'Sistem bisnis'],
            [2, 1, 2, 'Analisis Sistem', 'Fondasi', 'Analisis'],
            [3, 1, 3, 'Basis Data', 'Fondasi', 'Database'],
            [4, 1, 4, 'Manajemen Proyek', 'Profesional', 'Project'],
            [5, 1, 5, 'ERP', 'Profesional', 'Enterprise'],
            [6, 1, 6, 'Audit SI', 'Profesional', 'Evaluasi'],
            [7, 1, 7, 'Business Intelligence', 'Profesional', 'Data bisnis'],
            [8, 1, 8, 'Proyek Akhir', 'Profesional', 'Implementasi'],
            [9, 2, 1, 'Logika Pemrograman', 'Fondasi', 'Problem solving'],
            [10, 2, 2, 'Pemrograman Dasar', 'Fondasi', 'Coding'],
            [11, 2, 3, 'Struktur Data', 'Fondasi', 'Manajemen data'],
            [12, 2, 4, 'Basis Data', 'Fondasi', 'SQL'],
            [13, 2, 5, 'Pemrograman Web', 'Profesional', 'Fullstack'],
            [14, 2, 6, 'Jaringan Komputer', 'Profesional', 'Networking'],
            [15, 2, 7, 'Machine Learning', 'Profesional', 'AI dasar'],
            [16, 2, 8, 'Proyek Akhir', 'Profesional', 'Project real'],
            [17, 3, 1, 'Dasar IT', 'Fondasi', 'IT basic'],
            [18, 3, 2, 'Jaringan Komputer', 'Fondasi', 'Networking'],
            [19, 3, 3, 'Sistem Operasi', 'Fondasi', 'OS'],
            [20, 3, 4, 'Keamanan Sistem', 'Profesional', 'Security'],
            [21, 3, 5, 'Cloud Computing', 'Profesional', 'Cloud'],
            [22, 3, 6, 'DevOps', 'Profesional', 'Deployment'],
            [23, 3, 7, 'Virtualisasi', 'Profesional', 'Server'],
            [24, 3, 8, 'Proyek Akhir', 'Profesional', 'Infra IT'],
            [25, 4, 1, 'Anatomi', 'Fondasi', 'Tubuh manusia'],
            [26, 4, 2, 'Fisiologi', 'Fondasi', 'Fungsi organ'],
            [27, 4, 3, 'Biokimia', 'Fondasi', 'Kimia tubuh'],
            [28, 4, 4, 'Patologi', 'Profesional', 'Penyakit'],
            [29, 4, 5, 'Farmakologi', 'Profesional', 'Obat'],
            [30, 4, 6, 'Diagnostik', 'Profesional', 'Analisis'],
            [31, 4, 7, 'Koas', 'Profesional', 'Klinik'],
            [32, 4, 8, 'Ujian Profesi', 'Profesional', 'Lisensi'],
            [33, 5, 1, 'Dasar Keperawatan', 'Fondasi', 'Perawatan'],
            [34, 5, 2, 'Kebutuhan Dasar', 'Fondasi', 'Empati'],
            [35, 5, 3, 'Keperawatan Medikal', 'Fondasi', 'Pasien'],
            [36, 5, 4, 'Keperawatan Anak', 'Profesional', 'Spesialis'],
            [37, 5, 5, 'Keperawatan Jiwa', 'Profesional', 'Mental'],
            [38, 5, 6, 'Keperawatan Komunitas', 'Profesional', 'Masyarakat'],
            [39, 5, 7, 'Praktik Klinik', 'Profesional', 'Lapangan'],
            [40, 5, 8, 'Ujian Kompetensi', 'Profesional', 'Profesional'],
            [41, 6, 1, 'Psikologi Umum', 'Fondasi', 'Perilaku'],
            [42, 6, 2, 'Psikologi Perkembangan', 'Fondasi', 'Manusia'],
            [43, 6, 3, 'Psikologi Sosial', 'Fondasi', 'Interaksi'],
            [44, 6, 4, 'Psikologi Klinis', 'Profesional', 'Mental'],
            [45, 6, 5, 'Psikometri', 'Profesional', 'Tes'],
            [46, 6, 6, 'Konseling', 'Profesional', 'Komunikasi'],
            [47, 6, 7, 'Praktik Psikologi', 'Profesional', 'Observasi'],
            [48, 6, 8, 'Skripsi', 'Profesional', 'Riset'],
            [49, 7, 1, 'Dasar BK', 'Fondasi', 'Konseling'],
            [50, 7, 2, 'Psikologi Pendidikan', 'Fondasi', 'Siswa'],
            [51, 7, 3, 'Teknik Konseling', 'Fondasi', 'Komunikasi'],
            [52, 7, 4, 'Evaluasi BK', 'Profesional', 'Analisis'],
            [53, 7, 5, 'BK Individu', 'Profesional', 'Pendampingan'],
            [54, 7, 6, 'BK Kelompok', 'Profesional', 'Fasilitasi'],
            [55, 7, 7, 'Praktik BK', 'Profesional', 'Sekolah'],
            [56, 7, 8, 'Skripsi', 'Profesional', 'Riset'],
            [57, 8, 1, 'Pengantar Manajemen', 'Fondasi', 'Organisasi'],
            [58, 8, 2, 'Ekonomi', 'Fondasi', 'Ekonomi'],
            [59, 8, 3, 'Manajemen SDM', 'Fondasi', 'SDM'],
            [60, 8, 4, 'Manajemen Pemasaran', 'Profesional', 'Marketing'],
            [61, 8, 5, 'Manajemen Keuangan', 'Profesional', 'Finance'],
            [62, 8, 6, 'Perilaku Organisasi', 'Profesional', 'Psikologi kerja'],
            [63, 8, 7, 'Kewirausahaan', 'Profesional', 'Bisnis'],
            [64, 8, 8, 'Skripsi', 'Profesional', 'Analisis'],
            [65, 9, 1, 'Dasar Bisnis', 'Fondasi', 'Bisnis'],
            [66, 9, 2, 'Inovasi', 'Fondasi', 'Ide'],
            [67, 9, 3, 'Digital Marketing', 'Fondasi', 'Online'],
            [68, 9, 4, 'Manajemen Startup', 'Profesional', 'Startup'],
            [69, 9, 5, 'Branding', 'Profesional', 'Brand'],
            [70, 9, 6, 'Keuangan Bisnis', 'Profesional', 'Finance'],
            [71, 9, 7, 'Proyek Bisnis', 'Profesional', 'Eksekusi'],
            [72, 9, 8, 'Pitching', 'Profesional', 'Presentasi'],
            [73, 10, 1, 'Pengantar Akuntansi', 'Fondasi', 'Keuangan'],
            [74, 10, 2, 'Akuntansi Keuangan', 'Fondasi', 'Laporan'],
            [75, 10, 3, 'Akuntansi Biaya', 'Fondasi', 'Biaya'],
            [76, 10, 4, 'Perpajakan', 'Profesional', 'Pajak'],
            [77, 10, 5, 'Audit', 'Profesional', 'Pemeriksaan'],
            [78, 10, 6, 'SIA', 'Profesional', 'Sistem'],
            [79, 10, 7, 'Magang', 'Profesional', 'Kerja'],
            [80, 10, 8, 'Skripsi', 'Profesional', 'Analisis'],
            [81, 11, 1, 'Dasar Administrasi', 'Fondasi', 'Admin'],
            [82, 11, 2, 'Manajemen Kantor', 'Fondasi', 'Operasional'],
            [83, 11, 3, 'Komunikasi Bisnis', 'Fondasi', 'Komunikasi'],
            [84, 11, 4, 'Arsip', 'Profesional', 'Dokumen'],
            [85, 11, 5, 'Etika Bisnis', 'Profesional', 'Etika'],
            [86, 11, 6, 'Pelayanan', 'Profesional', 'Service'],
            [87, 11, 7, 'Magang', 'Profesional', 'Kerja'],
            [88, 11, 8, 'Laporan Akhir', 'Profesional', 'Evaluasi'],
            [89, 12, 1, 'Pengantar Publik', 'Fondasi', 'Pemerintah'],
            [90, 12, 2, 'Kebijakan Publik', 'Fondasi', 'Analisis'],
            [91, 12, 3, 'Manajemen Publik', 'Fondasi', 'Layanan'],
            [92, 12, 4, 'Hukum', 'Profesional', 'Regulasi'],
            [93, 12, 5, 'Etika Publik', 'Profesional', 'Integritas'],
            [94, 12, 6, 'Perencanaan', 'Profesional', 'Strategi'],
            [95, 12, 7, 'Magang', 'Profesional', 'Lapangan'],
            [96, 12, 8, 'Skripsi', 'Profesional', 'Riset'],
            [97, 13, 1, 'Dasar Desain', 'Fondasi', 'Visual'],
            [98, 13, 2, 'Tipografi', 'Fondasi', 'Teks'],
            [99, 13, 3, 'Desain Digital', 'Fondasi', 'Software'],
            [100, 13, 4, 'Ilustrasi', 'Profesional', 'Gambar'],
            [101, 13, 5, 'UI/UX', 'Profesional', 'App'],
            [102, 13, 6, 'Branding', 'Profesional', 'Identitas'],
            [103, 13, 7, 'Proyek', 'Profesional', 'Portofolio'],
            [104, 13, 8, 'Tugas Akhir', 'Profesional', 'Karya'],
            [105, 14, 1, 'Dasar Desain', 'Fondasi', 'Desain'],
            [106, 14, 2, 'Material', 'Fondasi', 'Bahan'],
            [107, 14, 3, 'Desain 3D', 'Fondasi', 'Model'],
            [108, 14, 4, 'Ergonomi', 'Profesional', 'User'],
            [109, 14, 5, 'CAD', 'Profesional', 'Software'],
            [110, 14, 6, 'Prototyping', 'Profesional', 'Produk'],
            [111, 14, 7, 'Proyek', 'Profesional', 'Implementasi'],
            [112, 14, 8, 'Tugas Akhir', 'Profesional', 'Karya'],
            [113, 15, 1, 'Dasar Seni', 'Fondasi', 'Seni'],
            [114, 15, 2, 'Menggambar', 'Fondasi', 'Visual'],
            [115, 15, 3, 'Melukis', 'Fondasi', 'Kreativitas'],
            [116, 15, 4, 'Seni Patung', 'Profesional', '3D'],
            [117, 15, 5, 'Seni Modern', 'Profesional', 'Eksplorasi'],
            [118, 15, 6, 'Kritik Seni', 'Profesional', 'Analisis'],
            [119, 15, 7, 'Pameran', 'Profesional', 'Presentasi'],
            [120, 15, 8, 'Tugas Akhir', 'Profesional', 'Karya'],
            [121, 16, 1, 'Fisika', 'Fondasi', 'Energi'],
            [122, 16, 2, 'Gambar Teknik', 'Fondasi', 'Desain'],
            [123, 16, 3, 'Material', 'Fondasi', 'Bahan'],
            [124, 16, 4, 'Termodinamika', 'Profesional', 'Panas'],
            [125, 16, 5, 'Fluida', 'Profesional', 'Aliran'],
            [126, 16, 6, 'Perancangan', 'Profesional', 'Design'],
            [127, 16, 7, 'Manufaktur', 'Profesional', 'Produksi'],
            [128, 16, 8, 'Skripsi', 'Profesional', 'Riset'],
            [129, 17, 1, 'Matematika', 'Fondasi', 'Hitung'],
            [130, 17, 2, 'Struktur', 'Fondasi', 'Bangunan'],
            [131, 17, 3, 'Material', 'Fondasi', 'Bahan'],
            [132, 17, 4, 'Geoteknik', 'Profesional', 'Tanah'],
            [133, 17, 5, 'Manajemen Proyek', 'Profesional', 'Proyek'],
            [134, 17, 6, 'Transportasi', 'Profesional', 'Infrastruktur'],
            [135, 17, 7, 'Konstruksi', 'Profesional', 'Lapangan'],
            [136, 17, 8, 'Skripsi', 'Profesional', 'Riset'],
            [137, 18, 1, 'Dasar Elektro', 'Fondasi', 'Listrik'],
            [138, 18, 2, 'Rangkaian', 'Fondasi', 'Analisis'],
            [139, 18, 3, 'Elektronika', 'Fondasi', 'Komponen'],
            [140, 18, 4, 'Digital', 'Profesional', 'Logika'],
            [141, 18, 5, 'Kontrol', 'Profesional', 'Otomasi'],
            [142, 18, 6, 'Telekomunikasi', 'Profesional', 'Sinyal'],
            [143, 18, 7, 'Praktikum', 'Profesional', 'Implementasi'],
            [144, 18, 8, 'Skripsi', 'Profesional', 'Riset'],
            [145, 19, 1, 'Dasar Otomotif', 'Fondasi', 'Mesin'],
            [146, 19, 2, 'Engine', 'Fondasi', 'Mesin'],
            [147, 19, 3, 'Kelistrikan', 'Fondasi', 'Listrik'],
            [148, 19, 4, 'Chassis', 'Profesional', 'Rangka'],
            [149, 19, 5, 'Diagnostik', 'Profesional', 'Analisis'],
            [150, 19, 6, 'Service', 'Profesional', 'Perbaikan'],
            [151, 19, 7, 'Bengkel', 'Profesional', 'Skill'],
            [152, 19, 8, 'Ujian', 'Profesional', 'Profesional'],
            [153, 20, 1, 'Pengantar Pendidikan', 'Fondasi', 'Edukasi'],
            [154, 20, 2, 'Psikologi Pendidikan', 'Fondasi', 'Siswa'],
            [155, 20, 3, 'Metode Mengajar', 'Fondasi', 'Teaching'],
            [156, 20, 4, 'Kurikulum', 'Profesional', 'Perencanaan'],
            [157, 20, 5, 'Media Pembelajaran', 'Profesional', 'Tools'],
            [158, 20, 6, 'Evaluasi', 'Profesional', 'Penilaian'],
            [159, 20, 7, 'Micro Teaching', 'Profesional', 'Praktek'],
            [160, 20, 8, 'Skripsi', 'Profesional', 'Riset']
        ];

        foreach ($data as $item) {
            Roadmap::updateOrCreate(
                ['id_roadmap' => $item[0]],
                [
                    'id_jurusan' => $item[1],
                    'semester' => $item[2],
                    'nama_matkul' => $item[3],
                    'kategori_matkul' => $item[4] ?: 'Fondasi', // Jika kosong default ke Fondasi
                    'skill_didapat' => $item[5],
                ]
            );
        }
    }
}